apiVersion: v1
kind: Service
metadata:
  name: hospital-frontend
  namespace: num
spec:
  type: ClusterIP
  selector:
    app: hospital-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
